version: "3"

services:
    jenkins:
      image: jenkins/jenkins:lts
      volumes:
        - jenkins_data:/var/jenkins_home
      ports:
        - '8080:8080'
        - '50000:50000'
      environment:
        - DOCKER_HOST=tcp://socat:2375
        - DOCKER_TLS_VERIFY=""
        - JAVA_OPTS=-Xmx1g
    clair:
        image: quay.io/coreos/clair:v2.1.8
        restart: unless-stopped
        volumes:
          - ./clair-config/:/config/:ro
          - ./clair-tmp/:/tmp/:rw
        ports:
          - '6060:6060'
          - '6061:6061'
        depends_on:
            - db1
        command: [-config=/config/config.yml]
        user: root
    sonarqube:
        image: sonarqube:community
        depends_on:
            - db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/db
            SONAR_JDBC_USERNAME: postgres
            SONAR_JDBC_PASSWORD: password
            SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
            SONAR_CE_JAVAOPTS: "-Xmx1G -Xms1G"
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
        ports:
            - "9000:9000"
    db:
        image: postgres:14
        ports:
          - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
    db1:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - postgresql1:/var/lib/postgresql
            - postgresql1_data:/var/lib/postgresql/data
volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql:
    postgresql_data:
    jenkins_data:
    clair-config:
    clair-tmp:
    postgresql1:
    postgresql1_data:
